.Dd March 8, 2025
.Dt README 7
.Os
.
.Sh NAME
.Nm h
.Nd H language frontend.
.
.Sh DESCRIPTION
H language frontend.
.
.Sh INSTALL
To compile and install run...
.Bd -literal -offset indent
sudo make
sudo make install

.Ed
 ...but you need permision to write in DESTDIR
.
.Sh EXAMPLES
See examples directory to get examples.
.
.Sh SEE ALSO
.Xr h 1
.Xr h 7
.
.Sh AUTHORS
.An gimura2022 Aq Mt gimura0001@gmail.com
